eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:1000/eureka
         
microservices:
   db-service:
      endpoints:
         endpoint:
            uri: http://db-service/db/
   product-service:
      endpoints:
         endpoint:
            uri: http://product-service/product/
   user-service:
      endpoints:
         endpoint:
            uri: http://user-service/user/
